os: linux
dist: trusty
language: generic
services:
  - docker

branches:
  only:
    - master

jobs:
  include:
    - stage: test-gui
      name: "Build Docker containers"
      script:
        - make deps
        - make gui-test

stages:
  - check-build