os: linux
dist: trusty
language: generic
services:
  - docker

branches:
  only:
    - master

jobs:
  include:
    - stage: check-build
      name: "Build Docker containers"
      script:
        - cd ./util/docker
        - make build_flask
        - make build_p4mn

stages:
  - check-build

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: cd ./util/docker && make push
  on:
    branch: master
